@hostname= localhost:3000

###
POST http://{{hostname}}/user_logout HTTP/1.1
content-type: application/json
Connection: keep
Date: {{$datetime iso8601}}

{
    "email": "990183536@qq.com",
    "token": "eyJ0b2tlbl9kYXRhIjp7ImxvZ2luX25hbWUiOiI5OTAxODM1MzZAcXEuY29tIn0sImNyZWF0ZWRfdGltZSI6MTU3ODU3MDM5OTU5NywiZWZmZWN0aXZlX3RpbWUiOjEwMDAwMDAwMH0=}.zMc+MooijMd0GU9eS5dlhwXAkfaThr9Cjarvo7xp3xg="
}
###
