@hostname= localhost:3000

###
POST http://{{hostname}}/user_logout HTTP/1.1
content-type: application/json
Connection: keep
Date: {{$datetime iso8601}}

{
    "email": "990183536@qq.com",
    "token": "eyJ0b2tlbl9kYXRhIjp7InVuaXF1ZSI6Ijk5MDE4MzUzNkBxcS5jb20ifSwiY3JlYXRlZF90aW1lIjoxNTgzMTQ2MzAyMjgyLCJlZmZlY3RpdmVfdGltZSI6NTAwMH0=.X+QULcFhVNE0gQqRnJmi/mxfakT47JJYKM4mxA+R7KA="
}
###
