@hostname= localhost:3000

###
POST http://{{hostname}}/OneWayFriendRelationship HTTP/1.1
content-type: application/json
Connection: keep
Date: {{$datetime iso8601}}

{
    "token": "eyJpZCI6IjE3Njk1OTI2MzEyIiwiY3JlYXRlVGltZSI6MTU5MjgzNjUzMjA0MSwidGltZW91dE1pbGxpc2Vjb25kQ29uc3QiOjIwMDAwfQ==.8qljpAgHMKVhk1ohnNmgKjuQD/bhFHM5i2dXYFaywpo=",
    "targetId": "18630977388"
}
###
