@address = http://localhost:3000
###

GET {{address}}/users HTTP/1.1

###

POST {{address}}/user_register HTTP/1.1
content-type: application/json
Connection: keep

{
    "telephone_number": "15584382922",
    "code": "81037",
    "nickname": "muduo",
    "password": "5a0528323662fd9cfdda9adc3eb85c88"
}

###
POST {{address}}/user_register_verification HTTP/1.1
content-type: application/json

{
    "telephone_number": "15584382922",
    "nickname": "muduo",
    "password": "5a0528323662fd9cfdda9adc3eb85c88"
}

###

POST {{address}}/user_register_by_telephone HTTP/1.1
content-type: application/json

{
    "telephone_number": 18630977388
}
